### ISSUE TITLE
文件未执行

### ISSUE THREAD

**Issue by xiaogouxion** [yzddmr6/ASP.NET-Memshell-Scanner#1]
以vulhub为测试环境进行测试，上传该文件web服务路径后，访问该文件，此文件直接以代码形式显示在界面中，并未检测到冰蝎生成的内存马，希望老哥能够指出操作失误的地方

![Uploading b70932ea745d436e1cd676e9fb3a7fc.png…]()

**Comment by yzddmr6** [comment]
你的图片没传成功，另外这是asp.net的内存马检测。
