### ISSUE TITLE
编译器错误消息:CS0103:The name 'current' does not exist in current context

### ISSUE THREAD

**Issue by zzgxpyy** [yzddmr6/ASP.NET-Memshell-Scanner#2]
行:84:while (current != null)
请问这是什么情况.

**Comment by yzddmr6** [comment]
请提供一下环境信息，.net版本，iis版本，服务器版本，是asp.net framework还是asp.net mvc等。

**Comment by zzgxpyy** [comment]
WIN10
VS2022.17.3.6
asp.net MVC
asp.net版本:4.8.4494
asp.net framework:4.0.30319
iisexpress 10.0
